# Generated by Django 4.0.6 on 2022-08-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='origin',
            field=models.CharField(default='origin', max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.CharField(default='origin', max_length=300),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=264, null=True, unique_for_date='published_at'),
        ),
    ]
